Fix 'bau check' on windows for yovo, document BS_MTEST_EXTRA
On mac and windows:
- Document BS_MTEST_EXTRA in help
- meson test is now verbose if -v is given

On windows:
- Add 'yotest killall' before building or testing yovo to avoid aborts
- no longer install pkgconfg, that's in yobuild13 now
- $btmp is now absolute to reduce confusion
- check for yotest was broken

diff --git a/bau-defaults/buildshim-osx b/bau-defaults/buildshim-osx
--- a/bau-defaults/buildshim-osx
+++ b/bau-defaults/buildshim-osx
@@ -54,6 +54,9 @@ Options:
 Localbuild options (can use , or space as separators):
   --lmirror "P,Q"   - Preload built packages P and Q from upstream apt/obs repo during lclone
   --lprojects "X,Y" - the projects lclone and lbuild will operate on
+
+Environment variables:
+BS_MTEST_EXTRA - With meson, to test just one suite, set to "--suite foo"
 _EOF_
 }
 
@@ -70,6 +73,12 @@ set_val() {
   then
     printf %s "$1" >> "$2"
   fi
+}
+
+if_verbose() {
+  case "$BAU_VERBOSE" in
+  [1-9]) echo "$1"
+  esac
 }
 
 # Parse options
@@ -128,9 +137,7 @@ parse_opts() {
     shift
   done
 
-  case "$BAU_VERBOSE" in
-  1) verbose=-v;;
-  esac
+  verbose=$(if_verbose -v)
 }
 
 do_patch() {
@@ -233,12 +240,19 @@ do_compile() {
 }
 
 do_check() {
+  # Since do_check uses verbose but doesn't call parse_opts, set it here.
+  local verbose=$(if_verbose -v)
   bs_test_env_setup
   cd "$btmp"
   if test -f ../meson.build
   then
-    if ! meson test -v $BS_MTEST_EXTRA
+    if ! meson test $verbose $BS_MTEST_EXTRA
     then
+      # If user didn't ask for verbose, and test fails, show the log
+      case "$BAU_VERBOSE" in
+      [1-9]) ;;
+      *) cat "$btmp"/meson-logs/testlog.txt;;
+      esac
       bs_abort "Test failed"
     fi
   elif test -f ../CMakeLists.txt
diff --git a/bau-defaults/buildshim-win b/bau-defaults/buildshim-win
--- a/bau-defaults/buildshim-win
+++ b/bau-defaults/buildshim-win
@@ -55,6 +55,9 @@ Options:
 Localbuild options (can use , or space as separators):
   --lmirror "P,Q"   - Preload built packages P and Q from upstream apt/obs repo during lclone
   --lprojects "X,Y" - the projects lclone and lbuild will operate on
+
+Environment variables:
+BS_MTEST_EXTRA - With meson, to test just one suite, set to "--suite foo"
 _EOF_
 }
 
@@ -71,6 +74,12 @@ set_val() {
   then
     printf %s "$1" >> "$2"
   fi
+}
+
+if_verbose() {
+  case "$BAU_VERBOSE" in
+  [1-9]) echo "$1"
+  esac
 }
 
 # Parse options
@@ -136,10 +145,7 @@ parse_opts() {
     esac
     shift
   done
-
-  case "$BAU_VERBOSE" in
-  1) verbose=-v;;
-  esac
+  verbose=$(if_verbose -v)
 }
 
 do_patch() {
@@ -211,22 +217,6 @@ install_cmake() {
   esac
 }
 
-PATH="$DRIVEC/pkg-config-lite/bin:$PATH"
-install_pkg_config() {
-  # FIXME: include pkgconf in windows yobuild, then remove pkg-config-lite
-  if ! test -d $DRIVEC/pkg-config-lite
-  then
-    # random old version we started with
-    rm -rf pkg-config-lite-0.28-1
-    scp git.oblong.com:/ob/buildtools/software/pkg-config-lite-0.28-1_bin-win32.zip .
-    unzip pkg-config-lite-0.28-1_bin-win32.zip
-    mkdir -p $DRIVEC/pkg-config-lite/bin
-    cp -a pkg-config-lite-0.28-1/bin/pkg-config.exe $DRIVEC/pkg-config-lite/bin
-    chmod +x $DRIVEC/pkg-config-lite/bin/pkg-config.exe
-    rm -rf pkg-config-lite-0.28-1
-  fi
-}
-
 PATH="$DRIVEC/Ruby24-x64/bin:$PATH"
 install_ruby() {
   if ! test -d $DRIVEC/Ruby24-x64
@@ -250,7 +240,6 @@ do_install_deps_base() {
   then
      install_cmake
   fi
-  install_pkg_config
   install_ruby
   zip --version > /dev/null || apt-cyg install zip
   unzip -v > /dev/null || apt-cyg install unzip
@@ -284,7 +273,7 @@ do_install_deps() {
 #-- end really windows specific cruft --
 
 can_meson() {
-  test -f "$origdir/meson.build" && meson --version
+  test -f "$origdir/meson.build" && meson --version > /dev/null
 }
 
 do_configure() {
@@ -346,6 +335,14 @@ do_compile() {
   local buildtype
   buildtype="$(bs_get_cmake_buildtype)"
 
+  # On some platforms, can't link if test fixtures still running
+  # FIXME: all mentions of yotest really should go in yovo's buildshim
+  # Oddly, on cygwin, -x fails even if yotest is marked +x.  Sigh.
+  if test -f "$btmp"/yotest
+  then
+    "$btmp"/yotest killall || true
+  fi
+
   bs_vcvars $bits
   if can_meson
   then
@@ -357,6 +354,8 @@ do_compile() {
 }
 
 do_check() {
+  # Since do_check uses verbose but doesn't call parse_opts, set it here.
+  local verbose=$(if_verbose -v)
   local buildtype
   buildtype="$(bs_get_cmake_buildtype)"
 
@@ -366,14 +365,26 @@ do_check() {
       return 0
   fi
 
+  # Kill old fixtures, just in case
+  # FIXME: all mentions of yotest really should go in yovo's buildshim
+  if test -f "$btmp"/yotest
+  then
+    "$btmp"/yotest killall || true
+  fi
+
   bs_vcvars $bits
   bs_test_env_setup
   if can_meson
   then
     cd "$btmp"
-    if ! meson test $BS_MTEST_EXTRA
+    if ! meson test $verbose $BS_MTEST_EXTRA
     then
       bs_test_env_teardown
+      # If user didn't ask for verbose, and test fails, show the log
+      case "$BAU_VERBOSE" in
+      [1-9]) ;;
+      *) cat meson-logs/testlog.txt;;
+      esac
       bs_abort "Test failed"
     fi
   else
@@ -683,7 +694,7 @@ bs_test_env_setup_base() {
 
   # If this project uses plasma, set up g-speak test environment
   # FIXME: let project's ci directory do this somehow
-  if can_meson && test -x "$btmp"/yotest
+  if can_meson && test -f "$btmp"/yotest
   then
     # This is yovo itself.  Let yotest set up the environment.
     "$btmp"/yotest start all
@@ -702,7 +713,7 @@ bs_test_env_setup() {
 
 bs_test_env_teardown() {
   # FIXME: let project's ci directory do this somehow
-  if can_meson && test -x "$btmp"/yotest
+  if can_meson && test -f "$btmp"/yotest
   then
     # This is yovo itself.  Let yotest tear down the environment.
     "$btmp"/yotest stop all
@@ -731,7 +742,7 @@ build) dir=$(dirname "$origdir");;
 esac
 # We used to put this in /cygdrive/c/builds, but that was hard to get right,
 # and with long path support, probably no longer needed.
-btmp=btmp
+btmp="$origdir"/btmp
 
 # FIXME: parse this from args?
 opt_toolchain=$(bs_detect_toolchain)
